export const COVERAGE_CITY_ZONES: Record<string, readonly string[]> = {
  Lagos: [
    'Ikeja',
    'Yaba',
    'Surulere',
    'Lekki',
    'Victoria Island',
    'Ikoyi',
    'Alimosho',
    'Kosofe',
    'Lagos Island',
    'Gbagada',
    'Maryland',
    'Ajah',
  ],
  Ibadan: [
    'Bodija',
    'Ring Road',
    'Dugbe',
    'Iyana Church',
    'Samonda',
    'Oluyole',
    'Mokola',
    'Agodi',
  ],
  'Abuja (FCT)': [
    'Garki',
    'Wuse',
    'Maitama',
    'Asokoro',
    'Jabi',
    'Utako',
    'Gwarinpa',
    'Kubwa',
  ],
  Abuja: [
    'Garki',
    'Wuse',
    'Maitama',
    'Asokoro',
    'Jabi',
    'Utako',
    'Gwarinpa',
    'Kubwa',
  ],
  'Port Harcourt': [
    'Port Harcourt GRA',
    'Rumuokoro',
    'Rumuogba',
    'D-Line',
    'Trans-Amadi',
    'Diobu',
    'Ada George',
  ],
  'Benin City': [
    'GRA Benin',
    'Uselu',
    'Ring Road',
    'Ikpoba Hill',
    'Ugbowo',
    'Ekenwan',
  ],
  Enugu: [
    'Independence Layout',
    'New Haven',
    'Ogui',
    'Achara Layout',
    'Abakpa Nike',
    'GRA Enugu',
  ],
  Kano: [
    'Nasarawa',
    'Fagge',
    'Dala',
    'Tarauni',
    'Gwale',
    'Kano Municipal',
  ],
};
