import { 
  TaskCategory, 
  ArtisanProfile, 
  TaskBooking, 
  ChatMessage, 
  ArtisanWallet, 
  AdminDispute 
} from '@bukiebrainjobs/types';

export const MOCK_CATEGORIES: TaskCategory[] = [
  {
    id: 'cat-1',
    slug: 'ac-repair',
    name: 'Air Conditioner (AC) Repair & Servicing',
    description: 'Gas refilling, compressor troubleshooting, deep coil washing, and fresh installation for split & window AC units.',
    iconName: 'Wind',
    averageRateNaira: 8500,
    isBinary: true,
    popularIn: ['Lagos Island', 'Lekki', 'Ikeja', 'Abuja Central', 'Port Harcourt GRA'],
  },
  {
    id: 'cat-2',
    slug: 'tv-mounting',
    name: 'TV & DSTV Wall Mounting',
    description: 'Precision wall mounting for OLED, Smart TVs, soundbars, DSTV dish alignment, and concealed cable trunking.',
    iconName: 'Tv',
    averageRateNaira: 6000,
    isBinary: true,
    popularIn: ['Victoria Island', 'Ikoyi', 'Gwarinpa', 'GRA Phase 2'],
  },
  {
    id: 'cat-3',
    slug: 'plumbing',
    name: 'Plumbing & Water Tank Fixes',
    description: 'Leaking pipes, tap installation, WC flush mechanism repair, water pump wiring, and GeePee tank plumbing.',
    iconName: 'Droplet',
    averageRateNaira: 7000,
    isBinary: true,
    popularIn: ['Surulere', 'Yaba', 'Maitama', 'Rumuogba'],
  },
  {
    id: 'cat-4',
    slug: 'electrical',
    name: 'Electrical & Inverter Setup',
    description: 'Socket repairs, distribution board wiring, changeover switch fix, solar inverter battery setup, and chandelier mounting.',
    iconName: 'Zap',
    averageRateNaira: 7500,
    isBinary: true,
    popularIn: ['Lekki Phase 1', 'Wuse 2', 'Trans Amadi'],
  },
  {
    id: 'cat-5',
    slug: 'handyman',
    name: 'General Handyman & Fix-It',
    description: 'Curtain rod installation, door lock replacement, cabinet hinge repair, mirror hanging, and home maintenance.',
    iconName: 'Wrench',
    averageRateNaira: 5000,
    isBinary: true,
    popularIn: ['Magodo', 'Ajah', 'Asokoro', 'Diobu'],
  },
  {
    id: 'cat-6',
    slug: 'furniture-assembly',
    name: 'Furniture & Flat-Pack Assembly',
    description: 'Wardrobe, bed frame, office desk, dining table assembly (IKEA, Fouani, and local custom furniture).',
    iconName: 'Package',
    averageRateNaira: 6500,
    isBinary: true,
    popularIn: ['Ikate', 'Jabi', 'Odili Road'],
  },
  {
    id: 'cat-7',
    slug: 'cleaning',
    name: 'Post-Construction & Deep Home Cleaning',
    description: 'Deep residential cleaning, post-renovation cleanup, short-let apartment turnaround, and carpet/sofa washing.',
    iconName: 'Sparkles',
    averageRateNaira: 12000,
    isBinary: false,
    popularIn: ['Lekki', 'Ikoyi', 'Maitama', 'GRA'],
  },
  {
    id: 'cat-8',
    slug: 'moving',
    name: 'Moving & Heavy Item Packing',
    description: 'Apartment relocation, heavy furniture moving, packing box supply, and van loading/unloading.',
    iconName: 'Truck',
    averageRateNaira: 15000,
    isBinary: true,
    popularIn: ['Gbagada', 'Ikeja', 'Utako', 'Eliozu'],
  },
  {
    id: 'cat-9',
    slug: 'painting',
    name: 'Interior & Exterior Painting',
    description: 'Screeding, POP painting, feature wall accenting, anti-damp treatment, and apartment repainting.',
    iconName: 'Paintbrush',
    averageRateNaira: 9000,
    isBinary: true,
    popularIn: ['Sangotedo', 'Lugbe', 'Aba Road'],
  },
  {
    id: 'cat-10',
    slug: 'generator-servicing',
    name: 'Generator Maintenance & Servicing',
    description: 'Oil change, carburetor cleaning, spark plug replacement, starter motor repairs for Mikano, Marapco, Thermocool, and Tiger gensets.',
    iconName: 'Settings',
    averageRateNaira: 8000,
    isBinary: true,
    popularIn: ['Allen Avenue', 'Garki 2', 'Rumuola'],
  },
];

export const MOCK_ARTISANS: ArtisanProfile[] = [
  {
    id: 'artisan-1',
    name: 'Emeka Okafor',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    phone: '+2348031234567',
    city: 'Lagos',
    area: 'Lekki Phase 1 / Ikate',
    categories: ['ac-repair', 'electrical', 'generator-servicing'],
    hourlyRateNaira: 8000,
    rating: 4.95,
    reviewCount: 142,
    completedTasksCount: 189,
    responseTimeMinutes: 12,
    acceptanceRatePercent: 98,
    completionRatePercent: 100,
    isBukieStar: true, // Top 15% Elite
    isSameHourAvailable: true,
    passportTier: 'Pro',
    bvnVerified: true,
    ninVerified: true,
    smartSelfieVerified: true,
    bio: 'Certified HVAC & Electrical technician with 7 years of experience servicing residential split units and industrial chillers across Lekki & VI.',
  },
  {
    id: 'artisan-2',
    name: 'Babatunde Adeleke',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    phone: '+2348029876543',
    city: 'Lagos',
    area: 'Ikeja / GRA / Maryland',
    categories: ['tv-mounting', 'furniture-assembly', 'handyman'],
    hourlyRateNaira: 6500,
    rating: 4.88,
    reviewCount: 96,
    completedTasksCount: 114,
    responseTimeMinutes: 18,
    acceptanceRatePercent: 95,
    completionRatePercent: 99,
    isBukieStar: true,
    isSameHourAvailable: false,
    passportTier: 'Lite',
    bvnVerified: true,
    ninVerified: true,
    smartSelfieVerified: true,
    bio: 'Specialist in flush TV wall mounting with hidden cable conduits and flat-pack furniture assembly.',
  },
  {
    id: 'artisan-3',
    name: 'Ibrahim Danjuma',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    phone: '+2348187654321',
    city: 'Abuja',
    area: 'Maitama / Wuse 2 / Jabi',
    categories: ['plumbing', 'handyman', 'ac-repair'],
    hourlyRateNaira: 7500,
    rating: 4.92,
    reviewCount: 78,
    completedTasksCount: 92,
    responseTimeMinutes: 15,
    acceptanceRatePercent: 97,
    completionRatePercent: 100,
    isBukieStar: true,
    isSameHourAvailable: true,
    passportTier: 'Pro',
    bvnVerified: true,
    ninVerified: true,
    smartSelfieVerified: true,
    bio: 'Master Plumber registered in Abuja. Expert in pressure pump installations, bathroom fixture upgrades, and emergency leak fixes.',
  },
  {
    id: 'artisan-4',
    name: 'Chinedu Briggs',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    phone: '+2348054321876',
    city: 'Port Harcourt',
    area: 'GRA Phase 2 / Odili Road',
    categories: ['generator-servicing', 'electrical', 'ac-repair'],
    hourlyRateNaira: 9000,
    rating: 4.85,
    reviewCount: 64,
    completedTasksCount: 76,
    responseTimeMinutes: 22,
    acceptanceRatePercent: 93,
    completionRatePercent: 98,
    isBukieStar: false,
    isSameHourAvailable: true,
    passportTier: 'Lite',
    bvnVerified: true,
    ninVerified: true,
    smartSelfieVerified: true,
    bio: 'Heavy-duty diesel and petrol generator mechanic specializing in Mikano, Perkins, and Firman generator maintenance.',
  },
];

export const MOCK_BOOKINGS: TaskBooking[] = [
  {
    id: 'booking-801',
    categorySlug: 'ac-repair',
    categoryName: 'Air Conditioner (AC) Repair & Servicing',
    clientId: 'client-101',
    clientName: 'Dr. Tunde Fashola',
    clientPhone: '+2348011112222',
    artisanId: 'artisan-1',
    artisanName: 'Emeka Okafor',
    artisanAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    artisanPhoneMasked: '+234 803 *** **67 (Masked via BukieBrain)',
    city: 'Lagos',
    address: 'Block 4, Flat 2, Admiralty Way, Lekki Phase 1',
    scheduledDate: '2026-08-03',
    scheduledTime: '10:00 AM',
    description: 'Master bedroom split AC is blowing warm air and leaking water along the indoor wall unit.',
    photoUrls: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=80'],
    status: 'artisan_en_route',
    urgency: 'Same-Day',
    artisanRateNaira: 8000,
    estimatedHours: 2,
    subtotalNaira: 16000,
    platformServiceFeeNaira: 2400, // 15%
    trustGuaranteeFeeNaira: 1200,   // 7.5%
    totalNaira: 19600,
    preAuthPaymentMethod: 'Paystack Card',
    preAuthStatus: 'Pre-Authorized',
    createdAt: '2026-08-02T09:30:00Z',
    updatedAt: '2026-08-02T10:15:00Z',
  },
  {
    id: 'booking-802',
    categorySlug: 'tv-mounting',
    categoryName: 'TV & DSTV Wall Mounting',
    clientId: 'client-102',
    clientName: 'Amina Bello',
    clientPhone: '+2348033334444',
    artisanId: 'artisan-2',
    artisanName: 'Babatunde Adeleke',
    artisanAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    artisanPhoneMasked: '+234 802 *** **43 (Masked via BukieBrain)',
    city: 'Lagos',
    address: '14 Isaac John Street, GRA Ikeja',
    scheduledDate: '2026-08-02',
    scheduledTime: '02:00 PM',
    description: 'Mount 65-inch Samsung OLED TV in living room on concrete wall with swivel bracket.',
    photoUrls: [],
    status: 'completed_and_paid',
    urgency: 'Normal',
    artisanRateNaira: 6500,
    estimatedHours: 1,
    subtotalNaira: 6500,
    platformServiceFeeNaira: 975,
    trustGuaranteeFeeNaira: 488,
    totalNaira: 7963,
    preAuthPaymentMethod: 'Paystack Transfer',
    preAuthStatus: 'Captured',
    invoiceHours: 1,
    finalInvoiceTotalNaira: 7963,
    createdAt: '2026-08-01T14:00:00Z',
    updatedAt: '2026-08-02T15:30:00Z',
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    bookingId: 'booking-801',
    senderId: 'artisan-1',
    senderName: 'Emeka Okafor',
    senderRole: 'artisan',
    text: 'Good morning Dr. Fashola, I have accepted your AC servicing request for Admiralty Way. I am en route now.',
    timestamp: '10:05 AM',
  },
  {
    id: 'msg-2',
    bookingId: 'booking-801',
    senderId: 'client-101',
    senderName: 'Dr. Tunde Fashola',
    senderRole: 'client',
    text: 'Great Emeka. Please ensure you come with R22 refrigerant gas in case it needs refilling.',
    timestamp: '10:08 AM',
  },
  {
    id: 'msg-3',
    bookingId: 'booking-801',
    senderId: 'artisan-1',
    senderName: 'Emeka Okafor',
    senderRole: 'artisan',
    text: 'Yes sir, I have R22 and R410a cylinders ready in my kit.',
    timestamp: '10:12 AM',
  },
];

export const MOCK_ARTISAN_WALLET: ArtisanWallet = {
  artisanId: 'artisan-1',
  availableBalanceNaira: 48000,
  pendingEscrowNaira: 16000,
  lifetimeEarningsNaira: 642000,
  payoutBankName: 'Guaranty Trust Bank (GTBank)',
  payoutAccountNumber: '0123456789',
  payoutAccountName: 'EMEKA OKAFOR',
  recentTransactions: [
    {
      id: 'tx-101',
      bookingId: 'booking-799',
      description: 'AC Gas Refill - Ikoyi Apartment',
      amountNaira: 16000,
      type: 'earning',
      status: 'completed',
      date: '2026-08-01',
    },
    {
      id: 'tx-102',
      bookingId: 'payout-40',
      description: 'Instant Payout to GTBank account ****6789',
      amountNaira: 32000,
      type: 'payout',
      status: 'completed',
      date: '2026-07-31',
    },
  ],
};

export const MOCK_ADMIN_DISPUTES: AdminDispute[] = [
  {
    id: 'disp-1',
    bookingId: 'booking-750',
    clientName: 'Chief Kenneth Nnamdi',
    artisanName: 'Samson Akpan',
    issueType: 'Off-Platform Solicitation',
    description: 'Artisan requested client to cancel booking and pay ₦15,000 cash directly to avoid platform fee.',
    status: 'Open Review',
    createdAt: '2026-08-02T08:15:00Z',
  },
  {
    id: 'disp-2',
    bookingId: 'booking-722',
    clientName: 'Nneka Eze',
    artisanName: 'Jide Ogunleye',
    issueType: 'Property Damage',
    description: 'Minor water pipe crack during bathroom faucet replacement. Claiming BukieGuarantee repair coverage of ₦25,000.',
    claimAmountNaira: 25000,
    status: 'Under Investigation',
    createdAt: '2026-08-01T16:40:00Z',
  },
];
