// apps/web/lib/brainworker/leads/invitations.ts
// BW-003 Phase 3 GREEN: Invitation Response Consumer (INV-001 to INV-010)
// Governed by: BW-003 Architecture Contract v1.0 & Test-First Implementation Plan v1.0
//
// Invariant Rules:
// 1. Zero imports from testing/ (REP-009 boundary).
// 2. Caller/session identity is authoritative; provider IDs are verified.
// 3. respondedAt is strictly generated by mutation authority, never client-authored.
// 4. Decline requires canonical taxonomy (SCHEDULE_CONFLICT, OUTSIDE_COVERAGE_AREA,
//    SKILL_TOOL_MISMATCH, RATE_BUDGET_MISMATCH, TEMPORARILY_UNAVAILABLE, OTHER).
// 5. Decline never cancels or alters underlying customer job state.
// 6. Consumer uses repository return state as authoritative, never inventing local state.

import type {
  DeclineReason,
  LeadMutationResult,
  IBrainWorkerLeadsRepository,
} from './types';
import { getBrainWorkerLeadsRepository } from './repository';

export interface InvitationResponseConsumer {
  accept(brainWorkerId: string, invitationId: string): Promise<LeadMutationResult>;
  decline(
    brainWorkerId: string,
    invitationId: string,
    reason: DeclineReason
  ): Promise<LeadMutationResult>;
}

export class DefaultInvitationResponseConsumer implements InvitationResponseConsumer {
  private readonly repository: IBrainWorkerLeadsRepository;

  constructor(repository?: IBrainWorkerLeadsRepository) {
    this.repository = repository ?? getBrainWorkerLeadsRepository();
  }

  async accept(
    brainWorkerId: string,
    invitationId: string
  ): Promise<LeadMutationResult> {
    return this.repository.acceptInvitation(brainWorkerId, invitationId);
  }

  async decline(
    brainWorkerId: string,
    invitationId: string,
    reason: DeclineReason
  ): Promise<LeadMutationResult> {
    return this.repository.declineInvitation(brainWorkerId, invitationId, reason);
  }
}

export function createInvitationResponseConsumer(
  repository?: IBrainWorkerLeadsRepository
): InvitationResponseConsumer {
  return new DefaultInvitationResponseConsumer(
    repository ?? getBrainWorkerLeadsRepository()
  );
}

export async function acceptLeadInvitation(
  brainWorkerId: string,
  invitationId: string,
  repository?: IBrainWorkerLeadsRepository
): Promise<LeadMutationResult> {
  const consumer = createInvitationResponseConsumer(repository);
  return consumer.accept(brainWorkerId, invitationId);
}

export async function declineLeadInvitation(
  brainWorkerId: string,
  invitationId: string,
  reason: DeclineReason,
  repository?: IBrainWorkerLeadsRepository
): Promise<LeadMutationResult> {
  const consumer = createInvitationResponseConsumer(repository);
  return consumer.decline(brainWorkerId, invitationId, reason);
}
