// apps/web/lib/brainworker/leads/invitations.ts
// BW-003 Phase 3 RED: Invitation Response Consumer (stub)
// Governed by: BW-003 Architecture Contract v1.0 & Test-First Implementation Plan v1.0
//
// Invariant Rules:
// 1. Zero imports from testing/ (REP-009 boundary).
// 2. Caller/session identity is authoritative; provider IDs are verified.
// 3. respondedAt is strictly generated by mutation authority, never client-authored.
// 4. Decline requires canonical taxonomy (SCHEDULE_CONFLICT, OUTSIDE_COVERAGE_AREA,
//    SKILL_TOOL_MISMATCH, RATE_BUDGET_MISMATCH, TEMPORARILY_UNAVAILABLE, OTHER).
// 5. Decline never cancels or alters underlying customer job state.
// 6. Consumer uses repository return state as authoritative, never inventing local state.

import type {
  DeclineReason,
  LeadMutationResult,
  IBrainWorkerLeadsRepository,
} from './types';
import { getBrainWorkerLeadsRepository } from './repository';

export interface InvitationResponseConsumer {
  accept(brainWorkerId: string, invitationId: string): Promise<LeadMutationResult>;
  decline(
    brainWorkerId: string,
    invitationId: string,
    reason: DeclineReason
  ): Promise<LeadMutationResult>;
}

export class DefaultInvitationResponseConsumer implements InvitationResponseConsumer {
  constructor(
    private readonly repository: IBrainWorkerLeadsRepository = getBrainWorkerLeadsRepository()
  ) {}

  async accept(
    _brainWorkerId: string,
    _invitationId: string
  ): Promise<LeadMutationResult> {
    throw new Error('RED: accept not implemented');
  }

  async decline(
    _brainWorkerId: string,
    _invitationId: string,
    _reason: DeclineReason
  ): Promise<LeadMutationResult> {
    throw new Error('RED: decline not implemented');
  }
}

export function createInvitationResponseConsumer(
  repository?: IBrainWorkerLeadsRepository
): InvitationResponseConsumer {
  return new DefaultInvitationResponseConsumer(repository);
}

export async function acceptLeadInvitation(
  brainWorkerId: string,
  invitationId: string,
  repository?: IBrainWorkerLeadsRepository
): Promise<LeadMutationResult> {
  const consumer = createInvitationResponseConsumer(repository);
  return consumer.accept(brainWorkerId, invitationId);
}

export async function declineLeadInvitation(
  brainWorkerId: string,
  invitationId: string,
  reason: DeclineReason,
  repository?: IBrainWorkerLeadsRepository
): Promise<LeadMutationResult> {
  const consumer = createInvitationResponseConsumer(repository);
  return consumer.decline(brainWorkerId, invitationId, reason);
}
